### ISSUE TITLE
[Bug]总是对响应进行验证而不是仅仅验证其长度

### ISSUE THREAD

**Issue by NaturalSelect** [iirose-tools/iirose-bot#4]
https://github.com/iirose-tools/iirose-bot/blob/1a0c92a9f328f5ef30296750321e59f879fb4c73/app/Controllers/AuthController.php#L24

**Comment by hs-err** [comment]
无法修复：响应返回的是13位uid

**Comment by NaturalSelect** [comment]
直接返回唯一的13位uid？

**Comment by hs-err** [comment]
> 直接返回唯一的13位uid？

是的，目前只能确定全部是数字+小写字母

**Comment by NaturalSelect** [comment]
> > 直接返回唯一的13位uid？
> 
> 是的，目前只能确定全部是数字+小写字母

那验证一下用户输入的uid与返回的uid是否相同
